## YAML Template.
---
login:
    path: /login
    defaults: { _controller: AppBundle:User:login }
    
login_check:
    path: /login_check
    
logout:
    path: /logout
    
user_register:
    path: /register
    defaults: { _controller: AppBundle:User:register }

user_dashboard:
    path: /dashboard
    defaults: { _controller: AppBundle:User:dashboard }
